services:
  discography-downloader:
    build: .
    container_name: discography_downloader
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
