import os
import subprocess
import re
from typing import List, Dict

class ProtocolService:
    def __init__(self, logger):
        self.logger = logger
        self.root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    def _run_git(self, args: List[str], cwd=None) -> str:
        if cwd is None:
            cwd = self.root_dir
        try:
            result = subprocess.run(
                ["git"] + args,
                cwd=cwd,
                capture_output=True,
                text=True,
                check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError as e:
            self.logger.error(f"Git command failed: git {' '.join(args)}\nError: {e.stderr}")
            raise Exception(f"Git error: {e.stderr}")

    async def sync_repository(self):
        """Step 1: Upstream Tracking & Submodule Sanitization."""
        self.logger.info("Starting Repository Synchronization...")

        # 1. Fetch All
        self.logger.info("Fetching all remotes and tags...")
        self._run_git(["fetch", "--all", "--tags"])

        # 2. Upstream Sync (assuming 'origin' is the main remote for this environment)
        # In a real environment, we might have an 'upstream' remote.
        # For this tool, we'll merge origin/main.
        self.logger.info("Merging origin/main...")
        self._run_git(["merge", "origin/main", "-m", "AI Protocol: Auto-sync with origin/main"])

        # 3. Recursive Submodule Update
        self.logger.info("Updating submodules recursively...")
        self._run_git(["submodule", "update", "--init", "--recursive"])

        self.logger.info("Repository synchronized successfully.")

    async def reconcile_branches(self):
        """Step 2: Dual-Direction Intelligent Merge Engine."""
        self.logger.info("Starting Branch Reconciliation...")

        # Ensure we are not in the middle of a merge
        if os.path.exists(os.path.join(self.root_dir, ".git", "MERGE_HEAD")):
            self.logger.warning("A merge is already in progress. Aborting reconciliation attempt.")
            return

        # Identify local feature branches (excluding main and current)
        branches_raw = self._run_git(["branch"]).split("\n")
        current_branch = ""
        feature_branches = []
        for b in branches_raw:
            b = b.strip()
            if b.startswith("* "):
                current_branch = b[2:]
            elif b and b != "main":
                feature_branches.append(b)

        self.logger.info(f"Current branch: {current_branch}")
        self.logger.info(f"Identified feature branches: {feature_branches}")

        # Forward Merge (Features to Main) - Only if we are on main
        if current_branch == "main":
            for fb in feature_branches:
                try:
                    self.logger.info(f"Attempting forward merge of {fb} into main...")
                    self._run_git(["merge", fb, "-m", f"AI Protocol: Forward merge {fb} into main"])
                except Exception as e:
                    self.logger.warning(f"Forward merge of {fb} failed (likely conflicts): {e}")
                    self._run_git(["merge", "--abort"])

        # Reverse Merge (Main back to Features)
        for fb in feature_branches:
            try:
                self.logger.info(f"Attempting reverse merge of main into {fb}...")
                # We need to checkout, merge, and come back
                self._run_git(["checkout", fb])
                self._run_git(["merge", "main", "-m", f"AI Protocol: Reverse merge main into {fb}"])
                self._run_git(["checkout", current_branch])
            except Exception as e:
                self.logger.warning(f"Reverse merge into {fb} failed: {e}")
                self._run_git(["checkout", current_branch])

        self.logger.info("Branch reconciliation complete.")

    async def extract_roadmap(self):
        """Step 3: Workspace Cleanup & Roadmap Extraction."""
        self.logger.info("Extracting Roadmap and TODOs...")

        # Identify gaps (mock implementation for pilot - in reality would use static analysis)
        todo_path = os.path.join(self.root_dir, "TODO.md")
        roadmap_path = os.path.join(self.root_dir, "ROADMAP.md")

        # Sample logic: search for TODO comments in code
        try:
            todos = subprocess.check_output(
                ["grep", "-rI", "TODO", os.path.join(self.root_dir, "discography_webapp")],
                text=True
            ).split("\n")
        except subprocess.CalledProcessError:
            todos = []

        with open(todo_path, "w") as f:
            f.write("# TODOs\n\n")
            f.write("Generated by AI Autonomous Protocol\n\n")
            for t in todos:
                if t:
                    f.write(f"- {t.strip()}\n")

        self.logger.info("Roadmap extraction complete.")
